### ISSUE TITLE
Je voudrais un tux teuffeur !!

### ISSUE THREAD

**Issue by JohannCahier** [PoggoAgency/Tux-Collection#4]
Et pas un punk à chien kétamineux, mais un bon manchot qui tape de la pate et qui sait pkoi !!

il aurait une casquette comme ça : https://i.skyrock.net/7755/57287755/pics/2340364617_1.jpg
(avec un ou spike dedans ^^)

des rangers (https://fr.wikipedia.org/wiki/Rangers_(chaussure)) mais il peut avoir le pantalon qui tombe dessus ! (je tiens VRAIMENT aux rangos)

Possible d'ici à mon annf ? C'est le 17...

**Comment by JohannCahier** [comment]
avec la main en l'air !

**Comment by JohannCahier** [comment]
(je fais un sweat avec s'il est bon !)

**Comment by PoggoAgency** [comment]
Oui ok ! 
Nous allons uploader des Tux écolier/écolière aujourd'hui pour la rentrée. On enchaîne sur le tiens après :)

**Comment by JohannCahier** [comment]
Pour l'inspiration : https://soundcloud.com/si-vandal-kaotik/radium-vandal-fatty-fatty
https://soundcloud.com/hardskull1/nareku-raggatek-minimix-1

Bon ceci dit, atta, j'ai balancé l'idée comme ça, sans en discuter avec "les chefs"... Si tu factures au Tux, et qu'ils me le retienne sur ma paye, ça va me faire drôle ^^

**Comment by PoggoAgency** [comment]
Il n'y a pas de soucis, ça en fera un de plus dans la collection !

**Comment by PoggoAgency** [comment]
<img width="698" alt="TUX TEUFEUR" src="https://user-images.githubusercontent.com/46819174/64357388-db58fe80-d004-11e9-9ae7-7af2b5f0ab1d.png">

**Comment by PoggoAgency** [comment]
S'il te convient, on uploade la version Inkscape avec les calques

**Comment by PoggoAgency** [comment]
Le Inkscape est uploadé dans la Tux-collection !
Si tu veux faire un sweatshirt avec, on te fournit un export jpeg ou pdf depuis la natif Illustrator, il y a une perte de rendu sur le svg Inkscape.

**Comment by JohannCahier** [comment]
Arf, je viens de voir... Pas de soucis remarque, il est nickel, merci !!

**Comment by JohannCahier** [comment]
(petits soucis de mails + en vacances ^^)

**Comment by JohannCahier** [comment]
Pour l'annif et le sweat y'a pas d'urgence en vrai !! Waww merci pour la réactivité !!

Voilà le morçal préféré de ce Tux !! https://www.youtube.com/watch?v=ybRjk9KKcT8

Quoique des fois il prèfère le trois temps des lapins tranceux : https://www.youtube.com/watch?v=X6lXZBT749w

Merci infiniment !! J'essaye d'imprimer avant la rentrée :)

**Comment by PoggoAgency** [comment]
Tiens-nous au courant quand on peut t'envoyer les bons fichiers pour impression !

**Comment by JohannCahier** [comment]
Hello,

Alors si je regarde en détail il y a un petit soucis avec le calque "tired eyes", les "cercles" rouges ne sont pas bien aligné avec le bord des yeux ! En taille normale sur l'écran ça se voit à peine, 1 ou 2 pixels, mais si on zoome ça devient évident. 
J'ai bien essayé de le drag & drop pensant que c'était juste le rouge en semi-transparance, mais en fait le calque inclue une copie des yeux et du bec, donc le déplacer résoud rien, au contraire :(

**Comment by PoggoAgency** [comment]
Voici un lien qui contient le nécessaire pour ton imprimeur : https://we.tl/t-qN2BOV2rPN
On regarde ce qui déconne dans le Inkscape et on fera une update

**Comment by JohannCahier** [comment]
Merci ! 
Après vérification... Pas de soucis d'alignment dans ces fichiers là !

Du coup je peux envoyer un des PDF à un imprimeur direct comme ça ?
Il sera bien en "transparence" ? (ce serait bête d'imprimer le fond blanc avec  ^^⁾

**Comment by PoggoAgency** [comment]
Oui, tu peux même lui envoyer tout le dossier selon sa façon de faire.
Il n'y aucun soucis pour imprimer en suivant le contour, explique bien ce que tu veux à la boutique qui imprime et normalement ils te montrent un visuel de ce que ça va donner.

Bon anniv en retard au fait ;)

**Comment by JohannCahier** [comment]
Merci !!

Ok, nickel, plus qu'à chercher un imprimeur alors !
Je pense qu'on peut fermer "l'issue" :)
